
CREATE DATABASE DBFACTURAS

USE DBFACTURAS

CREATE TABLE ARTICULOS
(
COD_ARTICULO int primary key,
DESCRIPCION text,
PESO decimal(6,2)
)

CREATE TABLE BODEGAS
(
COD_BODEGA int primary key,
LINEA int,
NOMBRE_BODEGA varchar(50),
EXISTENCIA int,
)

CREATE TABLE ARTICULO_BODEGA
(
COD_BODEGA int,  
COD_ARTICULO int,
FOREIGN KEY (COD_BODEGA) REFERENCES BODEGAS(COD_BODEGA),
FOREIGN KEY (COD_ARTICULO) REFERENCES ARTICULOS(COD_ARTICULO),
)

CREATE TABLE COBRADOR
(
ID_COBRADOR nvarchar(15) primary key,
NOMBRE_COBRADOR text
)

CREATE TABLE VENDEDORES
(ID_VENDEDOR nvarchar(15) primary key,
NOMBRE text,
FOTOGRAFIA image
) 

--DROP TABLE FACTURA

CREATE TABLE FACTURA
(TIPO_FACTURA char(1) NOT NULL,
 NO_FACTURA char(12) NOT NULL,
ID_VENDEDOR nvarchar(15),
ID_COBRADOR nvarchar(15),
ASIENTO_CONTABLE char(10),
COMISION decimal(13,2),
TOTAL_PESO decimal(13,2),
IMPUESTO decimal(13,2),
FECHA date,
MONTO_DESCUENTO decimal(13,2),
PORC_DESCUENTO decimal(13,2),
TOTAL_FACTURA decimal(13,2),
DIRECCION_FACTURA char(1),
SIGNO decimal(13,2),
OBSERVACIONES char(1),
USUARIO_CREADOR char(10),
TIPO_CAMBIO date,
FCONTROL_CREACION date,
FCONTROL_MODIFICACION date,
VALOR_IVA float
FOREIGN KEY (ID_COBRADOR) references COBRADOR(ID_COBRADOR),
FOREIGN KEY(ID_VENDEDOR) references VENDEDORES(ID_VENDEDOR),
)

ALTER TABLE FACTURA add constraint PK_FACTURA primary key (TIPO_FACTURA, NO_FACTURA)

CREATE TABLE FACTURA_DETALLE
(
LINEA int primary key,
TIPO_FACTURA char(1),
NO_FACTURA char(12),
COD_ARTICULO int,
CANTIDAD int,
PRECIO_UNITARIO decimal(13,2),
TOTAL_IMPUESTO_1 decimal(13,2),
DESC_TOT_GENERAL decimal(13,2),
COSTO_TOTAL decimal(13,2),
PRECIO_TOTAL decimal(13,2),
FOREIGN KEY (COD_ARTICULO) REFERENCES ARTICULOS(COD_ARTICULO),
)

ALTER TABLE FACTURA_DETALLE add constraint FK_FACTURA FOREIGN KEY (TIPO_FACTURA, NO_FACTURA) REFERENCES FACTURA(TIPO_FACTURA, NO_FACTURA)

--tipos de usuarios
---ingenuos (consultas), programador (), sofisticados(jefes), otros 

